using Fuse.Fusion.Scoping;
using Fuse.Collection.Models;
using Fuse.Collection.Options;
using Fuse.Collection.Templates;
using Fuse.Emission.Models;
using Fuse.Plugins.Abstractions.Options;

namespace Fuse.Fusion;

/// <summary>
///     Builds <see cref="FusionRequest" /> instances with fluent configuration and template resolution.
/// </summary>
/// <remarks>
///     Open-ended task localization and other query-path retrieval knobs live in <c>Fuse.Retrieval</c>, not
///     in <see cref="ExperimentalOptions" />. The builder's experimental surface covers only focus/change
///     scoping and emission shaping consumed by the fusion pipeline.
///     Extension and exclusion lists are resolved during <see cref="Build" /> using the same rules
///     as the legacy configuration resolver:
///     <list type="number">
///         <item><description><c>OnlyExtensions</c> overrides all template and include settings.</description></item>
///         <item><description>When no template is specified, defaults to include extensions or <c>*.*</c>.</description></item>
///         <item><description>When a template is specified, template defaults are merged with user overrides.</description></item>
///     </list>
/// </remarks>
public sealed class FusionRequestBuilder
{
    private readonly ProjectTemplateRegistry? _templateRegistry;

    private string? _sourceDirectory;
    private ProjectTemplate? _template;
    private List<string>? _includeExtensions;
    private List<string>? _excludeExtensions;
    private List<string>? _onlyExtensions;
    private List<string>? _excludeDirectories;
    private List<string>? _excludeFiles;
    private List<string>? _excludePatterns;
    private int _maxFileSizeKb = 0;
    private bool _recursive = true;
    private bool _ignoreBinaryFiles = true;
    private bool _excludeEmptyFiles = true;
    private bool _excludeAutoGenerated = true;
    private bool _excludeTestProjects = false;
    private bool _excludeUnitTestProjects = false;
    private bool _respectGitIgnore = true;
    private ReductionOptions _reductionOptions = new();
    private EmissionOptions _emissionOptions = new();
    private bool _inMemory = false;
    private FocusOptions? _focusOptions;
    private ChangeOptions? _changeOptions;
    private int _parallelism = Environment.ProcessorCount;
    private bool _useReductionCache = true;
    private bool _clearReductionCache = false;
    private bool _useAnalysisCache = false;
    private List<string>? _explicitFiles;
    private ExperimentalOptions? _experimental;

    /// <summary>
    ///     Initializes a new instance of the <see cref="FusionRequestBuilder" /> class.
    /// </summary>
    public FusionRequestBuilder()
    {
    }

    /// <summary>
    ///     Initializes a new instance of the <see cref="FusionRequestBuilder" /> class with a template registry.
    /// </summary>
    /// <param name="templateRegistry">The registry used to resolve project template defaults.</param>
    public FusionRequestBuilder(ProjectTemplateRegistry templateRegistry)
    {
        _templateRegistry = templateRegistry;
    }

    /// <summary>
    ///     Sets the root directory to scan for source files.
    /// </summary>
    /// <param name="sourceDirectory">The source directory path.</param>
    /// <returns>The current builder instance.</returns>
    public FusionRequestBuilder WithSourceDirectory(string sourceDirectory)
    {
        _sourceDirectory = sourceDirectory;
        return this;
    }

    /// <summary>
    ///     Collects exactly the given file paths instead of walking the source directory.
    /// </summary>
    /// <param name="files">File paths, absolute or relative to the source directory.</param>
    /// <returns>The current builder instance.</returns>
    /// <remarks>
    ///     Bypasses directory enumeration and the include/exclude filters. The source directory is still required
    ///     (it anchors relative paths, the analysis base, and git operations). Used by the reduce path.
    /// </remarks>
    public FusionRequestBuilder WithExplicitFiles(IEnumerable<string> files)
    {
        _explicitFiles = files.ToList();
        return this;
    }

    /// <summary>
    ///     Sets the project template used to resolve default extensions and exclusions.
    /// </summary>
    /// <param name="template">The project template.</param>
    /// <returns>The current builder instance.</returns>
    public FusionRequestBuilder WithTemplate(ProjectTemplate template)
    {
        _template = template;
        return this;
    }

    /// <summary>
    ///     Adds file extensions to include beyond template defaults.
    /// </summary>
    /// <param name="extensions">The extensions to include, including leading dots.</param>
    /// <returns>The current builder instance.</returns>
    public FusionRequestBuilder WithIncludeExtensions(params string[] extensions)
    {
        _includeExtensions ??= new List<string>();
        _includeExtensions.AddRange(extensions);
        return this;
    }

    /// <summary>
    ///     Removes file extensions from the resolved include list when a template is used.
    /// </summary>
    /// <param name="extensions">The extensions to exclude, including leading dots.</param>
    /// <returns>The current builder instance.</returns>
    public FusionRequestBuilder WithExcludeExtensions(params string[] extensions)
    {
        _excludeExtensions ??= new List<string>();
        _excludeExtensions.AddRange(extensions);
        return this;
    }

    /// <summary>
    ///     Restricts collection to only the specified extensions, overriding template defaults entirely.
    /// </summary>
    /// <param name="extensions">The only extensions to include, including leading dots.</param>
    /// <returns>The current builder instance.</returns>
    public FusionRequestBuilder WithOnlyExtensions(params string[] extensions)
    {
        _onlyExtensions ??= new List<string>();
        _onlyExtensions.AddRange(extensions);
        return this;
    }

    /// <summary>
    ///     Adds directory names to exclude from scanning.
    /// </summary>
    /// <param name="directories">The directory names to exclude.</param>
    /// <returns>The current builder instance.</returns>
    public FusionRequestBuilder WithExcludeDirectories(params string[] directories)
    {
        _excludeDirectories ??= new List<string>();
        _excludeDirectories.AddRange(directories);
        return this;
    }

    /// <summary>
    ///     Adds specific file names to exclude from the collection.
    /// </summary>
    /// <param name="files">The file names to exclude.</param>
    /// <returns>The current builder instance.</returns>
    public FusionRequestBuilder WithExcludeFiles(params string[] files)
    {
        _excludeFiles ??= new List<string>();
        _excludeFiles.AddRange(files);
        return this;
    }

    /// <summary>
    ///     Adds glob patterns that exclude matching files from the collection.
    /// </summary>
    /// <param name="patterns">The glob patterns to exclude.</param>
    /// <returns>The current builder instance.</returns>
    public FusionRequestBuilder WithExcludePatterns(params string[] patterns)
    {
        _excludePatterns ??= new List<string>();
        _excludePatterns.AddRange(patterns);
        return this;
    }

    /// <summary>
    ///     Sets the maximum file size in kilobytes for collected files.
    /// </summary>
    /// <param name="maxFileSizeKb">The maximum file size in KB; zero means unlimited.</param>
    /// <returns>The current builder instance.</returns>
    public FusionRequestBuilder WithMaxFileSizeKb(int maxFileSizeKb)
    {
        _maxFileSizeKb = maxFileSizeKb;
        return this;
    }

    /// <summary>
    ///     Sets collection behavior flags for scanning and filtering.
    /// </summary>
    /// <param name="recursive">Whether to scan subdirectories.</param>
    /// <param name="ignoreBinaryFiles">Whether to skip binary files.</param>
    /// <param name="excludeEmptyFiles">Whether to skip zero-byte files.</param>
    /// <param name="excludeAutoGenerated">Whether to skip auto-generated files.</param>
    /// <param name="excludeTestProjects">Whether to exclude all test project directories.</param>
    /// <param name="excludeUnitTestProjects">Whether to exclude unit test project directories.</param>
    /// <param name="respectGitIgnore">Whether to honor <c>.gitignore</c> rules.</param>
    /// <returns>The current builder instance.</returns>
    public FusionRequestBuilder WithCollectionBehavior(
        bool recursive = true,
        bool ignoreBinaryFiles = true,
        bool excludeEmptyFiles = true,
        bool excludeAutoGenerated = true,
        bool excludeTestProjects = false,
        bool excludeUnitTestProjects = false,
        bool respectGitIgnore = true)
    {
        _recursive = recursive;
        _ignoreBinaryFiles = ignoreBinaryFiles;
        _excludeEmptyFiles = excludeEmptyFiles;
        _excludeAutoGenerated = excludeAutoGenerated;
        _excludeTestProjects = excludeTestProjects;
        _excludeUnitTestProjects = excludeUnitTestProjects;
        _respectGitIgnore = respectGitIgnore;
        return this;
    }

    /// <summary>
    ///     Applies collection options, overwriting builder state for all collection-related settings.
    /// </summary>
    /// <param name="options">The collection options to apply.</param>
    /// <returns>The current builder instance.</returns>
    public FusionRequestBuilder WithCollectionOptions(CollectionOptions options)
    {
        _sourceDirectory = options.SourceDirectory;
        _template = options.Template;
        _includeExtensions = options.Extensions.Count > 0 ? options.Extensions.ToList() : null;
        _excludeDirectories = options.ExcludeDirectories.Count > 0 ? options.ExcludeDirectories.ToList() : null;
        _excludeFiles = options.ExcludeFiles.Count > 0 ? options.ExcludeFiles.ToList() : null;
        _excludePatterns = options.ExcludePatterns.Count > 0 ? options.ExcludePatterns.ToList() : null;
        _maxFileSizeKb = options.MaxFileSizeKb;
        _recursive = options.Recursive;
        _ignoreBinaryFiles = options.IgnoreBinaryFiles;
        _excludeEmptyFiles = options.ExcludeEmptyFiles;
        _excludeAutoGenerated = options.ExcludeAutoGenerated;
        _excludeTestProjects = options.ExcludeTestProjects;
        _excludeUnitTestProjects = options.ExcludeUnitTestProjects;
        _respectGitIgnore = options.RespectGitIgnore;
        return this;
    }

    /// <summary>
    ///     Sets the reduction options for content normalization and minification.
    /// </summary>
    /// <param name="options">The reduction options.</param>
    /// <returns>The current builder instance.</returns>
    public FusionRequestBuilder WithReductionOptions(ReductionOptions options)
    {
        _reductionOptions = options;
        return this;
    }

    /// <summary>
    ///     Sets the emission options for output generation and token budgeting.
    /// </summary>
    /// <param name="options">The emission options.</param>
    /// <returns>The current builder instance.</returns>
    public FusionRequestBuilder WithEmissionOptions(EmissionOptions options)
    {
        _emissionOptions = options;
        return this;
    }

    /// <summary>
    ///     Sets whether output is captured in memory instead of written to disk.
    /// </summary>
    /// <param name="inMemory">Whether to use in-memory output.</param>
    /// <returns>The current builder instance.</returns>
    public FusionRequestBuilder WithInMemory(bool inMemory = true)
    {
        _inMemory = inMemory;
        return this;
    }

    /// <summary>
    ///     Sets dependency-aware focus scoping options.
    /// </summary>
    /// <param name="focusOptions">The focus options, or <c>null</c> to disable.</param>
    /// <returns>The current builder instance.</returns>
    public FusionRequestBuilder WithFocusOptions(FocusOptions? focusOptions)
    {
        _focusOptions = focusOptions;
        return this;
    }

    /// <summary>
    ///     Sets git change-scoped fusion options.
    /// </summary>
    /// <param name="changeOptions">The change options, or <c>null</c> to disable.</param>
    /// <returns>The current builder instance.</returns>
    public FusionRequestBuilder WithChangeOptions(ChangeOptions? changeOptions)
    {
        _changeOptions = changeOptions;
        return this;
    }

    /// <summary>
    ///     Sets the maximum degree of parallelism for pipeline stages.
    /// </summary>
    /// <param name="parallelism">The parallelism degree; must be at least 1.</param>
    /// <returns>The current builder instance.</returns>
    public FusionRequestBuilder WithParallelism(int parallelism)
    {
        _parallelism = parallelism;
        return this;
    }

    /// <summary>
    ///     Sets reduction cache behavior for the fusion run.
    /// </summary>
    /// <param name="useCache">Whether to read and write reduction cache entries in host memory.</param>
    /// <param name="clearCache">Whether to clear cached reduction entries for the source repository before fusion runs.</param>
    /// <returns>The current builder instance.</returns>
    public FusionRequestBuilder WithReductionCacheOptions(bool useCache, bool clearCache = false)
    {
        _useReductionCache = useCache;
        _clearReductionCache = clearCache;
        return this;
    }

    /// <summary>
    ///     Enables or disables the host-memory analysis cache.
    /// </summary>
    /// <param name="useAnalysisCache">Whether to cache per-file dependency and symbol analysis in host memory.</param>
    /// <returns>The current builder instance.</returns>
    public FusionRequestBuilder WithAnalysisCache(bool useAnalysisCache)
    {
        _useAnalysisCache = useAnalysisCache;
        return this;
    }

    /// <summary>
    ///     Sets experimental knobs for focus/change scoping and emission shaping on the fusion run.
    /// </summary>
    /// <param name="experimental">The experimental options, or <c>null</c> to use defaults.</param>
    /// <returns>The current builder instance.</returns>
    public FusionRequestBuilder WithExperimentalOptions(ExperimentalOptions? experimental)
    {
        _experimental = experimental;
        return this;
    }

    /// <summary>
    ///     Builds the fusion request after resolving extensions and exclusions.
    /// </summary>
    /// <returns>A configured <see cref="FusionRequest" />.</returns>
    /// <exception cref="FusionValidationException">Thrown when builder state is invalid.</exception>
    /// <exception cref="InvalidOperationException">Thrown when a template is specified but no registry was provided.</exception>
    public FusionRequest Build()
    {
        var builderErrors = FusionValidator.ValidateBuilderState(
            _template.HasValue,
            _onlyExtensions?.Count > 0);

        if (builderErrors.Count > 0)
        {
            throw new FusionValidationException(builderErrors);
        }

        if (string.IsNullOrWhiteSpace(_sourceDirectory))
        {
            throw new FusionValidationException("Source directory is required.");
        }

        var collection = ResolveCollectionOptions();

        return new FusionRequest(
            collection,
            _reductionOptions,
            _emissionOptions,
            _inMemory,
            _focusOptions,
            _changeOptions,
            _parallelism,
            _useReductionCache,
            _clearReductionCache,
            _useAnalysisCache,
            _experimental);
    }

    private CollectionOptions ResolveCollectionOptions()
    {
        IReadOnlyCollection<string> extensions;
        IReadOnlyCollection<string> excludeDirectories;
        IReadOnlyCollection<string> excludePatterns;
        ProjectTemplate? resolvedTemplate = _template;

        if (_onlyExtensions?.Count > 0)
        {
            extensions = _onlyExtensions.Distinct().ToArray();
            excludeDirectories = _excludeDirectories ?? [];
            excludePatterns = _excludePatterns ?? [];
            resolvedTemplate = null;
        }
        else if (!_template.HasValue)
        {
            extensions = _includeExtensions?.Count > 0
                ? _includeExtensions.Distinct().ToArray()
                : ["*.*"];
            excludeDirectories = _excludeDirectories ?? [];
            excludePatterns = _excludePatterns ?? [];
        }
        else
        {
            if (_templateRegistry is null)
            {
                throw new InvalidOperationException(
                    "A ProjectTemplateRegistry is required to resolve template defaults. " +
                    "Construct FusionRequestBuilder with a registry or register services via AddFuseCore.");
            }

            var template = _templateRegistry.GetTemplate(_template!.Value);
            var extensionList = template.Extensions.ToList();
            var excludeDirectoryList = template.ExcludeDirectories.ToList();

            if (_excludeExtensions is not null)
            {
                extensionList = extensionList.Except(_excludeExtensions).ToList();
            }

            if (_includeExtensions is not null)
            {
                extensionList.AddRange(_includeExtensions);
            }

            if (_excludeDirectories is not null)
            {
                excludeDirectoryList.AddRange(_excludeDirectories);
            }

            var patternList = template.ExcludePatterns.ToList();
            if (_excludePatterns is not null)
            {
                patternList.AddRange(_excludePatterns);
            }

            extensions = extensionList.Distinct().ToArray();
            excludeDirectories = excludeDirectoryList.Distinct().ToArray();
            excludePatterns = patternList.Distinct().ToArray();
        }

        return new CollectionOptions(
            _sourceDirectory!,
            resolvedTemplate,
            extensions,
            excludeDirectories,
            _excludeFiles ?? [],
            excludePatterns,
            _maxFileSizeKb,
            _recursive,
            _ignoreBinaryFiles,
            _excludeEmptyFiles,
            _excludeAutoGenerated,
            _excludeTestProjects,
            _excludeUnitTestProjects,
            _respectGitIgnore)
        {
            ExplicitFiles = _explicitFiles
        };
    }
}
