using Fuse.Collection;
using Fuse.Collection.FileSystem;
using Fuse.Collection.Filters;
using Fuse.Indexing;
using Fuse.Semantics;
using Xunit;

namespace Fuse.Semantics.Tests;

// P2.1: file discovery + hash records via FileCollectionPipeline, with test/generated flags.
public sealed class WorkspaceFileScannerTests : IDisposable
{
    private readonly string _root =
        Path.Combine(Path.GetTempPath(), "fuse-semantics-tests", Guid.NewGuid().ToString("N"));

    public WorkspaceFileScannerTests()
    {
        Directory.CreateDirectory(Path.Combine(_root, "src"));
        Directory.CreateDirectory(Path.Combine(_root, "tests"));
        Directory.CreateDirectory(Path.Combine(_root, "bin"));
        File.WriteAllText(Path.Combine(_root, "src", "OrderService.cs"), "namespace App; public class OrderService { }");
        File.WriteAllText(Path.Combine(_root, "src", "Generated.g.cs"), "// <auto-generated/>\nnamespace App; class G { }");
        File.WriteAllText(Path.Combine(_root, "tests", "OrderServiceTests.cs"), "using Xunit; public class OrderServiceTests { }");
        File.WriteAllText(Path.Combine(_root, "bin", "Skip.cs"), "class ShouldBeExcluded { }");
    }

    [Fact]
    public async Task ScanFindsSourceFilesWithHashes()
    {
        var scanner = CreateScanner();

        var records = await scanner.ScanAsync(new FileScanRequest(_root), CancellationToken.None);

        var order = Assert.Single(records, r => r.NormalizedPath.EndsWith("src/OrderService.cs", StringComparison.Ordinal));
        Assert.Equal(".cs", order.Extension);
        Assert.False(string.IsNullOrEmpty(order.ContentHash));
        Assert.False(order.IsTest);
        Assert.False(order.IsGenerated);
    }

    [Fact]
    public async Task ScanFlagsTestAndGeneratedFiles()
    {
        var scanner = CreateScanner();

        var records = await scanner.ScanAsync(new FileScanRequest(_root), CancellationToken.None);

        Assert.True(records.Single(r => r.NormalizedPath.EndsWith("OrderServiceTests.cs", StringComparison.Ordinal)).IsTest);
        Assert.True(records.Single(r => r.NormalizedPath.EndsWith("Generated.g.cs", StringComparison.Ordinal)).IsGenerated);
    }

    [Fact]
    public async Task ScanExcludesBinDirectory()
    {
        var scanner = CreateScanner();

        var records = await scanner.ScanAsync(new FileScanRequest(_root), CancellationToken.None);

        Assert.DoesNotContain(records, r => r.NormalizedPath.Contains("/bin/", StringComparison.Ordinal));
    }

    [Fact]
    public async Task ScanExcludesClaudeWorktrees()
    {
        // A Claude Code worktree is a full duplicate of the repo under .claude/worktrees; its sources must not
        // be indexed, or retrieval returns copies of every file (the reported .claude/worktrees pollution).
        var worktree = Path.Combine(_root, ".claude", "worktrees", "wf_1", "src");
        Directory.CreateDirectory(worktree);
        File.WriteAllText(Path.Combine(worktree, "OrderService.cs"), "namespace App; public class OrderService { }");

        var scanner = CreateScanner();

        var records = await scanner.ScanAsync(new FileScanRequest(_root), CancellationToken.None);

        Assert.DoesNotContain(records, r => r.NormalizedPath.Contains(".claude", StringComparison.Ordinal));
    }

    [Fact]
    public async Task ScanExcludesNestedRepository()
    {
        // A nested checkout (a directory carrying its own .git) is a separate repo; its sources must not be
        // collected as part of this workspace, regardless of the directory's name.
        var nested = Path.Combine(_root, "external", "Lib");
        Directory.CreateDirectory(nested);
        File.WriteAllText(Path.Combine(nested, ".git"), "gitdir: /elsewhere/.git/worktrees/lib");
        File.WriteAllText(Path.Combine(nested, "Lib.cs"), "namespace Lib; public class Lib { }");

        var scanner = CreateScanner();

        var records = await scanner.ScanAsync(new FileScanRequest(_root), CancellationToken.None);

        Assert.DoesNotContain(records, r => r.NormalizedPath.Contains("external/Lib", StringComparison.Ordinal));
    }

    [Fact]
    public async Task ScanProducesStableHashForUnchangedFile()
    {
        var scanner = CreateScanner();

        var first = await scanner.ScanAsync(new FileScanRequest(_root), CancellationToken.None);
        var second = await scanner.ScanAsync(new FileScanRequest(_root), CancellationToken.None);

        var firstHash = first.Single(r => r.NormalizedPath.EndsWith("src/OrderService.cs", StringComparison.Ordinal)).ContentHash;
        var secondHash = second.Single(r => r.NormalizedPath.EndsWith("src/OrderService.cs", StringComparison.Ordinal)).ContentHash;
        Assert.Equal(firstHash, secondHash);
    }

    private static WorkspaceFileScanner CreateScanner()
    {
        var fileSystem = new PhysicalFileSystem();
        var pipeline = new FileCollectionPipeline(
            fileSystem,
            new GitIgnoreParser(fileSystem),
            [
                new GitIgnoreFilter(),
                new ExtensionFilter(),
                new ExcludedDirectoryFilter(),
                new EmptyFileFilter(),
                new BinaryFileFilter(fileSystem),
            ]);
        return new WorkspaceFileScanner(pipeline);
    }

    public void Dispose()
    {
        try
        {
            if (Directory.Exists(_root))
                Directory.Delete(_root, recursive: true);
        }
        catch (IOException)
        {
            // Best-effort cleanup of temp test artifacts.
        }
    }
}
