namespace Fuse.Semantics;

/// <summary>
///     Classifies discovered files as test or generated, using path and content-prefix heuristics.
/// </summary>
/// <remarks>
///     These flags steer retrieval (test files are de-emphasized unless requested; generated files are
///     rendered as a sketch). The heuristics are deliberately cheap: a path test plus a scan of a short
///     content prefix, not a full parse.
/// </remarks>
public static class FileClassifier
{
    private static readonly string[] TestPathMarkers = ["/tests/", "/test/", ".tests/", ".tests.", ".test."];
    private static readonly string[] TestContentMarkers =
        ["[Fact]", "[Theory]", "[Test]", "[TestMethod]", "using Xunit", "using NUnit", "Microsoft.VisualStudio.TestTools"];
    private static readonly string[] GeneratedContentMarkers =
        ["<auto-generated", "auto-generated>", "This code was generated", "<autogenerated", "GeneratedCodeAttribute"];
    private static readonly string[] GeneratedPathSuffixes =
        [".g.cs", ".designer.cs", ".generated.cs", ".g.i.cs", ".assemblyinfo.cs"];
    private static readonly string[] GeneratedPathSegments = ["/generated/", "/autogenerated/"];

    /// <summary>
    ///     Determines whether a file is a test file.
    /// </summary>
    /// <param name="normalizedPath">The forward-slash relative path.</param>
    /// <param name="contentPrefix">A short prefix of the file content.</param>
    /// <returns><c>true</c> when the path or content indicates a test file.</returns>
    public static bool IsTestFile(string normalizedPath, string contentPrefix)
    {
        var lower = normalizedPath.ToLowerInvariant();
        var fileName = GetFileName(lower);
        if (fileName.EndsWith("tests.cs", StringComparison.Ordinal) ||
            fileName.EndsWith("specs.cs", StringComparison.Ordinal) ||
            fileName.EndsWith("test.cs", StringComparison.Ordinal))
        {
            return true;
        }

        foreach (var marker in TestPathMarkers)
        {
            if (lower.Contains(marker, StringComparison.Ordinal))
                return true;
        }

        foreach (var marker in TestContentMarkers)
        {
            if (contentPrefix.Contains(marker, StringComparison.Ordinal))
                return true;
        }

        return false;
    }

    /// <summary>
    ///     Determines whether a file is generated.
    /// </summary>
    /// <param name="normalizedPath">The forward-slash relative path.</param>
    /// <param name="contentPrefix">A short prefix of the file content.</param>
    /// <returns><c>true</c> when the path or content indicates a generated file.</returns>
    public static bool IsGenerated(string normalizedPath, string contentPrefix)
    {
        var lower = normalizedPath.ToLowerInvariant();
        foreach (var suffix in GeneratedPathSuffixes)
        {
            if (lower.EndsWith(suffix, StringComparison.Ordinal))
                return true;
        }

        foreach (var segment in GeneratedPathSegments)
        {
            if (lower.Contains(segment, StringComparison.Ordinal))
                return true;
        }

        // EF Core model snapshots and migrations designer files are generated.
        if (lower.Contains("/migrations/", StringComparison.Ordinal) &&
            lower.EndsWith("modelsnapshot.cs", StringComparison.Ordinal))
        {
            return true;
        }

        foreach (var marker in GeneratedContentMarkers)
        {
            if (contentPrefix.Contains(marker, StringComparison.Ordinal))
                return true;
        }

        return false;
    }

    private static string GetFileName(string path)
    {
        var slash = path.LastIndexOf('/');
        return slash >= 0 ? path[(slash + 1)..] : path;
    }
}
