using System.Buffers;
using System.Security.Cryptography;
using System.Text;
using Fuse.Collection;
using Fuse.Collection.Options;
using Fuse.Indexing;

namespace Fuse.Semantics;

/// <summary>
///     Discovers source files in a workspace and produces <see cref="IndexedFileRecord" /> values with
///     content hashes and test/generated flags, ready to upsert into the index.
/// </summary>
/// <remarks>
///     Reuses <see cref="FileCollectionPipeline" /> for discovery (gitignore, extension, and exclusion
///     rules), then reuses clean Git blob ids or streams a SHA-256 hash for working-tree files. Generated files
///     are classified from their path and an 8 KiB content prefix.
///     Test and generated files are included and flagged, not excluded: retrieval decides how to treat
///     them.
/// </remarks>
public sealed class WorkspaceFileScanner
{
    private const int ContentPrefixBytes = 8 * 1024;
    private const int HashBufferBytes = 64 * 1024;

    /// <summary>
    ///     The default per-file size cap (bytes) above which a file retains inventory metadata only. A generated
    ///     giant or a mislabeled binary would otherwise cost memory and time for no useful syntax signal.
    ///     Override with the <c>FUSE_MAX_FILE_BYTES</c> environment variable.
    /// </summary>
    public const long DefaultMaxFileBytes = 5L * 1024 * 1024;

    /// <summary>The environment variable overriding <see cref="DefaultMaxFileBytes" />.</summary>
    public const string MaxFileBytesEnvVar = "FUSE_MAX_FILE_BYTES";

    private static readonly string[] DefaultExtensions = [".cs", ".csproj", ".props", ".targets", ".json"];

    private readonly FileCollectionPipeline _pipeline;
    // For a Git work tree, use Git's inventory instead of a raw directory walk. It excludes ignored trees and
    // provides clean blob ids, so unchanged tracked source does not need a full content hash.
    private readonly GitFileEnumerator _gitFiles = new();

    /// <summary>
    ///     Initializes a new instance of the <see cref="WorkspaceFileScanner" /> class.
    /// </summary>
    /// <param name="pipeline">The collection pipeline used to discover files.</param>
    public WorkspaceFileScanner(FileCollectionPipeline pipeline)
    {
        _pipeline = pipeline;
    }

    /// <summary>
    ///     Discovers files under a root directory and builds their index records.
    /// </summary>
    /// <param name="request">The scan request.</param>
    /// <param name="cancellationToken">A token to cancel the scan.</param>
    /// <returns>The discovered files as index records, sorted by the pipeline's deterministic path order.</returns>
    public async Task<IReadOnlyList<IndexedFileRecord>> ScanAsync(FileScanRequest request, CancellationToken cancellationToken) =>
        (await ScanWithSkipsAsync(request, cancellationToken)).Files;

    /// <summary>
    ///     Discovers files under a root directory and builds their index records, also reporting the files skipped
    ///     (unreadable or permission-denied) so one hostile file never aborts the index (R35).
    /// </summary>
    /// <param name="request">The scan request.</param>
    /// <param name="cancellationToken">A token to cancel the scan.</param>
    /// <returns>The index records and the skipped files with reasons.</returns>
    public async Task<FileScanResult> ScanWithSkipsAsync(FileScanRequest request, CancellationToken cancellationToken)
    {
        // Prefer Git's own view of the working tree; null (not a Git repo) falls back to the directory walk.
        var gitInventory = await _gitFiles.TryDescribeAsync(request.RootDirectory, cancellationToken);

        var options = new CollectionOptions(
            sourceDirectory: request.RootDirectory,
            extensions: (request.Extensions ?? DefaultExtensions).ToArray(),
            excludeDirectories: WorkspaceExclusions.LoadDirectoryNames(request.RootDirectory).ToArray(),
            recursive: true,
            ignoreBinaryFiles: true,
            excludeEmptyFiles: true,
            // Generated and test files are indexed (and flagged), not dropped, so retrieval can reason about them.
            excludeAutoGenerated: false,
            excludeTestProjects: false,
            excludeUnitTestProjects: false,
            respectGitIgnore: true,
            candidateFiles: gitInventory?.Paths);

        var collection = await _pipeline.CollectAsync(options, cancellationToken);
        var records = new List<IndexedFileRecord>(collection.Files.Count);
        var skipped = new List<SkippedFile>();
        var detailLimited = new List<DetailLimitedFile>();
        var maxFileBytes = ResolveMaxFileBytes();

        foreach (var file in collection.Files)
        {
            cancellationToken.ThrowIfCancellationRequested();

            try
            {
                var blobId = gitInventory?.GetCleanBlobId(file.NormalizedRelativePath);
                var probe = await ProbeFileAsync(file.FullPath, blobId, cancellationToken);
                var isGenerated = FileClassifier.IsGenerated(file.NormalizedRelativePath, probe.Prefix);
                var detailLevel = maxFileBytes > 0 && file.FileInfo.Length > maxFileBytes
                    ? IndexDetailLevel.InventoryOnly
                    : isGenerated ? IndexDetailLevel.Declarations : IndexDetailLevel.Full;

                records.Add(new IndexedFileRecord(
                    Path: file.RelativePath,
                    NormalizedPath: file.NormalizedRelativePath,
                    Extension: file.Extension,
                    SizeBytes: file.FileInfo.Length,
                    MtimeUtcTicks: file.FileInfo.LastWriteTimeUtc.Ticks,
                    ContentHash: probe.ContentHash,
                    IsGenerated: isGenerated,
                    IsTest: FileClassifier.IsTestFile(file.NormalizedRelativePath, probe.Prefix),
                    DetailLevel: detailLevel));

                if (detailLevel == IndexDetailLevel.InventoryOnly)
                {
                    detailLimited.Add(new DetailLimitedFile(
                        file.NormalizedRelativePath,
                        detailLevel,
                        $"too large ({file.FileInfo.Length} bytes > {maxFileBytes} cap)"));
                }
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or System.Security.SecurityException)
            {
                skipped.Add(new SkippedFile(file.NormalizedRelativePath, $"{ex.GetType().Name}: {ex.Message}"));
            }
        }

        return new FileScanResult(records, skipped, detailLimited);
    }

    // The per-file size cap from FUSE_MAX_FILE_BYTES, or the default; a non-positive override disables the cap.
    private static long ResolveMaxFileBytes() =>
        long.TryParse(Environment.GetEnvironmentVariable(MaxFileBytesEnvVar), out var bytes) ? bytes : DefaultMaxFileBytes;

    private async Task<FileContentProbe> ProbeFileAsync(
        string path,
        string? cleanBlobId,
        CancellationToken cancellationToken)
    {
        await using var stream = new FileStream(
            path,
            FileMode.Open,
            FileAccess.Read,
            FileShare.Read,
            HashBufferBytes,
            FileOptions.Asynchronous | FileOptions.SequentialScan);

        var header = new byte[ContentPrefixBytes];
        var headerLength = 0;
        if (cleanBlobId is not null)
        {
            while (headerLength < header.Length)
            {
                var read = await stream.ReadAsync(header.AsMemory(headerLength), cancellationToken);
                if (read == 0)
                    break;
                headerLength += read;
            }

            return new FileContentProbe($"git:{cleanBlobId}", DecodePrefix(header, headerLength));
        }

        var buffer = ArrayPool<byte>.Shared.Rent(HashBufferBytes);
        try
        {
            using var hash = IncrementalHash.CreateHash(HashAlgorithmName.SHA256);
            while (true)
            {
                var read = await stream.ReadAsync(buffer.AsMemory(0, HashBufferBytes), cancellationToken);
                if (read == 0)
                    break;

                hash.AppendData(buffer, 0, read);
                var headerRemaining = header.Length - headerLength;
                if (headerRemaining > 0)
                {
                    var copyLength = Math.Min(headerRemaining, read);
                    Buffer.BlockCopy(buffer, 0, header, headerLength, copyLength);
                    headerLength += copyLength;
                }
            }

            return new FileContentProbe(
                "sha256:" + Convert.ToHexString(hash.GetHashAndReset()).ToLowerInvariant(),
                DecodePrefix(header, headerLength));
        }
        finally
        {
            ArrayPool<byte>.Shared.Return(buffer);
        }
    }

    // Decode a UTF-8 prefix for the test/generated content heuristics, skipping a BOM if present.
    private static string DecodePrefix(byte[] bytes, int byteCount)
    {
        var start = 0;
        if (byteCount >= 3 && bytes[0] == 0xEF && bytes[1] == 0xBB && bytes[2] == 0xBF)
            start = 3;

        var length = Math.Min(ContentPrefixBytes, byteCount - start);
        return length <= 0 ? string.Empty : Encoding.UTF8.GetString(bytes, start, length);
    }

    private sealed record FileContentProbe(string ContentHash, string Prefix);
}

/// <summary>
///     A request to scan a workspace for indexable files.
/// </summary>
/// <param name="RootDirectory">The workspace root to scan.</param>
/// <param name="Extensions">The file extensions to include; defaults to the .NET source and config set when null.</param>
public sealed record FileScanRequest(
    string RootDirectory,
    IReadOnlyCollection<string>? Extensions = null);

/// <summary>
///     The result of a workspace scan: the indexable file records, and the files skipped with the reason each was
///     skipped (R35), so one hostile file never aborts the index and the skips are visible in doctor.
/// </summary>
/// <param name="Files">The files that were read and turned into index records.</param>
/// <param name="Skipped">The unreadable or permission-denied files skipped during inventory.</param>
/// <param name="DetailLimited">Files retained at declarations or inventory-only detail, with their reasons.</param>
public sealed record FileScanResult(
    IReadOnlyList<IndexedFileRecord> Files,
    IReadOnlyList<SkippedFile> Skipped,
    IReadOnlyList<DetailLimitedFile> DetailLimited);

/// <summary>A file the scanner skipped during indexing, with the reason (R35).</summary>
/// <param name="Path">The file's normalized relative path.</param>
/// <param name="Reason">A short human-readable reason (IO error or access denied).</param>
public sealed record SkippedFile(string Path, string Reason);

/// <summary>A file whose retained index detail is intentionally limited, with the reason.</summary>
/// <param name="Path">The file's normalized relative path.</param>
/// <param name="DetailLevel">The stored level of index detail.</param>
/// <param name="Reason">The reason full source detail was not retained.</param>
public sealed record DetailLimitedFile(string Path, IndexDetailLevel DetailLevel, string Reason);
